#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# gen-secrets.sh — generate UDF backend key material ON THE SERVER.
# ═══════════════════════════════════════════════════════════════════════════
# Creates (under /etc/udf, root-owned):
#   • jwt_private.pem / jwt_public.pem  — RS256 access-token signing key pair
#   • secrets.env                       — LOCAL_KEK + BLIND_INDEX_KEY (64 hex each)
#
# Secret VALUES ARE NEVER PRINTED. Existing files are kept unless --force.
# The systemd unit loads secrets.env as a second EnvironmentFile and references
# the JWT PEMs by path (JWT_PRIVATE_KEY_PATH / JWT_PUBLIC_KEY_PATH).
#
# Usage:  sudo bash deploy/scripts/gen-secrets.sh [--force]
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

UDF_ETC=/etc/udf
APP_GROUP=udf                 # created by provision-server.sh
FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

if [[ $EUID -ne 0 ]]; then echo "Run as root (sudo)." >&2; exit 1; fi

# Create the config dir; tolerate the group not existing yet (provision first).
install -d -m 750 "$UDF_ETC"
chgrp "$APP_GROUP" "$UDF_ETC" 2>/dev/null || true

PRIV="$UDF_ETC/jwt_private.pem"
PUB="$UDF_ETC/jwt_public.pem"
if [[ -f "$PRIV" && $FORCE -eq 0 ]]; then
  echo "• JWT private key already exists: $PRIV  (pass --force to regenerate)"
else
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$PRIV"
  # 640 root:udf — the API (running as the `udf` user) reads this key at runtime
  # via JWT_PRIVATE_KEY_PATH, so the group needs read access.
  chmod 640 "$PRIV"; chgrp "$APP_GROUP" "$PRIV" 2>/dev/null || true
  openssl rsa -in "$PRIV" -pubout -out "$PUB"
  chmod 644 "$PUB"
  echo "• Generated RS256 key pair:"
  echo "    $PRIV   (chmod 640 root:$APP_GROUP — signing key, keep secret)"
  echo "    $PUB    (verification public key)"
fi

SECRETS="$UDF_ETC/secrets.env"
if [[ -f "$SECRETS" && $FORCE -eq 0 ]]; then
  echo "• Secrets file already exists: $SECRETS  (pass --force to regenerate)"
else
  KEK="$(openssl rand -hex 32)"
  BIDX="$(openssl rand -hex 32)"
  ( umask 077; cat > "$SECRETS" <<EOF
# Generated by deploy/scripts/gen-secrets.sh — DO NOT COMMIT. chmod 600.
# Loaded by udf-api.service as a second EnvironmentFile.
LOCAL_KEK=$KEK
BLIND_INDEX_KEY=$BIDX
EOF
  )
  chmod 600 "$SECRETS"; chgrp "$APP_GROUP" "$SECRETS" 2>/dev/null || true
  echo "• Wrote LOCAL_KEK + BLIND_INDEX_KEY to $SECRETS (values not shown)."
fi

echo
echo "Next steps:"
echo "  1. Ensure udf-api.service loads BOTH env files:"
echo "       EnvironmentFile=/etc/udf/udf-api.env"
echo "       EnvironmentFile=$SECRETS"
echo "  2. BACK UP $UDF_ETC offline (jwt_private.pem + secrets.env)."
echo "     Losing them invalidates all sessions and makes sealed PII /"
echo "     blind-index lookups unrecoverable."
